# Success
curl -X GET http://localhost:8000/favicon/http:duckduckgo.com
curl -X GET http://localhost:8000/favicon/http:apple.com
curl -X GET http://localhost:8000/favicon/http:google.com
curl -X GET http://localhost:8000/favicon/http:alfredforum.com
curl -X GET http://localhost:8000/favicon/https:gmail.com
curl -X GET http://localhost:8000/favicon/http:gmail.com
curl -X GET http://localhost:8000/favicon/http:github.com
curl -X GET http://localhost:8000/favicon/http:squarespace.com
curl -X GET http://localhost:8000/favicon/https:news.google.com
curl -X GET http://localhost:8000/favicon/http:kwild.co
curl -X GET http://localhost:8000/favicon/http:grafana.com
curl -X GET http://localhost:8000/favicon/http:fail.com
curl -X GET http://localhost:8000/favicon/http:libbyapp.com
curl -X GET http://localhost:8000/favicon/https:flights.google.com
curl -X GET http://localhost:8000/favicon/http:learn.acloud.guru/browse
curl -X GET http://localhost:8000/favicon/http:cnn.com
curl -X GET http://localhost:8000/favicon/http:duckduckgo.atlassian.net/
curl -X GET http://localhost:8000/favicon/https:udemy.com

# Failure
curl -X GET http://localhost:8000/favicon/http:duckduckkkgo.com
curl -X GET http://localhost:8000/favicon/http:apple.comm
curl -X GET http://localhost:8000/favicon/http:google.com
curl -X GET http://localhost:8000/favicon/htttp:alfredforum.com
curl -X GET http://localhost:8000/favicon/https:gmailly.com
curl -X GET http://localhost:8000/favicon/httpss:gmail.com
curl -X GET http://localhost:8000/favicon/http:github.cdom
curl -X GET http://localhost:8000/favicon/http:squarespace.com
curl -X GET http://localhost:8000/favicon/https:nfgews.google.com
curl -X GET http://localhost:8000/favicon/http:kwildf.cos
curl -X GET http://localhost:8000/favicon/http:grafanad.com
curl -X GET http://localhost:8000/favicon/http:fail.c
curl -X GET http://localhost:8000/favicon/http:libbyappppp.com
curl -X GET http://localhost:8000/favicon/https:fligddhts.google.com
curl -X GET http://localhost:8000/favicon/http:learn.agscloud.guru/browse
curl -X GET http://localhost:8000/favicon/http:cnn.dcom
curl -X GET http://localhost:8000/favicon/http:duckduckgo.atlasssssian.net/
curl -X GET http://localhost:8000/favicon/https:udedmy.com