{
 "title": "Favicon Fetcher API Service Dashboard",
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "method",
    "query": "label_values(http_requests_total, method)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Requests per Second",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_requests_total{handler=\"/favicon/{url:path}\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes*100"
    }
   ]
  }
 ]
}