global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['favicon-fetcher:8000']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

